implement storing messages to maildir
staktrace/maildir pull request #2
Opened 2017-05-12 16:29 UTC by dario23

wrote some code in response to #1 

i'm not entirely sure the custom error type is justified, but in using it seems easier than the rather weird type quantification before, and the rust book seems to recommend custom error type enums for this case. depending on what you think you can only apply the first two, or if you want i can change the other maildir functions to return `MaildirError` as well that currently return `io::Error`.

on the dependencies side i only had to add `nix`, existing software i looked at (dovecot and courier IMAP) don't seem to use random values as part of the generated filenames, so i didn't either.

2017-05-15 19:00 UTC, staktrace commented
Sorry for the delay here. I just moved and the packing/unpacking is taking up a lot of my time. I'll get to these as soon as I can, probably closer to the middle of this week.

2017-05-18 15:52 UTC, staktrace requested changes

2017-05-18 15:52 UTC, staktrace commented on src/lib.rs
> +            thread::sleep(time::Duration::from_secs(2));
A 2 second sleep seems a bit much. We're using nanoseconds in the timestamp so I think even a 10ms sleep should probably be ok here.

2017-05-18 15:52 UTC, staktrace commented on src/lib.rs
> +        std::fs::rename(tmppath, newpath)?;
It's highly unlikely that the `newpath` already exists, but if it does it's going to get clobbered. I'd prefer checking to see if it exists, and just bailing out with an error if it does.

2017-05-18 15:52 UTC, staktrace commented on src/lib.rs
> +
nit: Just one blank line between functions please

2017-05-18 15:54 UTC, staktrace approved these changes

2017-05-18 15:54 UTC, staktrace commented on src/lib.rs
> +Delivered-To: of82ecuq@cip.cs.fau.de
Probably better to use fake email addresses here. Once it goes into the revision history it'll be there forever.

2017-05-18 15:55 UTC, staktrace approved these changes

2017-05-18 15:59 UTC, staktrace approved these changes

2017-05-18 15:59 UTC, staktrace commented on src/lib.rs
> +
nit: Single line between functions

2017-05-18 16:00 UTC, staktrace commented
Thanks for the patches! I'm a little new to using github's reviewing tool so sorry if I'm not following conventions. The patches look pretty good except for the minor things I pointed out above. If you submit updated patches (force-push with the changes applied to the patches in-place) I'll be happy to merge.

2017-06-11 17:24 UTC, staktrace commented
@dario23 ping, are you planning to update the patches?

2017-06-16 13:21 UTC, dario23 commented
sorry, been offline for a while; just pushed updated patchset :-)

2017-06-16 14:53 UTC, staktrace commented
Looks like the build is failing, maybe need `Duration::milliseconds` instead of `Duration::from_millis`?

2017-06-18 19:44 UTC, dario23 commented
fixed that one, sorry for the extra round-trip

2017-06-19 13:32 UTC, merged

2017-06-19 13:32 UTC, staktrace commented
Merged, thanks!